In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

In [2]:
# Import our input dataset
attrition_df = pd.read_csv('Resources/HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [3]:
# Generate our categorical variable list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [4]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [5]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

C:\Users\kcaul\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

C:\Users\kcaul\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

C:\Users\kcaul\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [8]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [9]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

In [11]:
# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 448

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [12]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [13]:
# Train the model
fit_model = nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
35/35 [==============================] - 1s 1ms/step - loss: 584.3094 - accuracy: 0.2232
Epoch 2/100
35/35 [==============================] - 0s 1ms/step - loss: 47.1786 - accuracy: 0.6960
Epoch 3/100
35/35 [==============================] - 0s 1ms/step - loss: 22.2708 - accuracy: 0.7196
Epoch 4/100
35/35 [==============================] - 0s 1ms/step - loss: 15.8093 - accuracy: 0.7541
Epoch 5/100
35/35 [==============================] - ETA: 0s - loss: 25.2704 - accuracy: 0.656 - 0s 1ms/step - loss: 11.7803 - accuracy: 0.7514
Epoch 6/100
35/35 [==============================] - 0s 1ms/step - loss: 10.3821 - accuracy: 0.7722
Epoch 7/100
35/35 [==============================] - 0s 1ms/step - loss: 9.6625 - accuracy: 0.7323
Epoch 8/100
35/35 [==============================] - 0s 1ms/step - loss: 7.7896 - accuracy: 0.7559
Epoch 9/100
35/35 [==============================] - 0s 1ms/step - loss: 7.2326 - accuracy: 0.7323
Epoch 10/100
35/35 [==============================] - 0s 2ms/step - loss: 7.2734 - accuracy: 0.7659
Epoch 11/100
35/35 [==============================] - 0s 1ms/step - loss: 6.0905 - accuracy: 0.7441
Epoch 12/100
35/35 [==============================] - 0s 1ms/step - loss: 5.1037 - accuracy: 0.7459
Epoch 13/100
35/35 [==============================] - 0s 1ms/step - loss: 5.0461 - accuracy: 0.7677
Epoch 14/100
35/35 [==============================] - 0s 1ms/step - loss: 3.7787 - accuracy: 0.7604
Epoch 15/100
35/35 [==============================] - 0s 1ms/step - loss: 3.7434 - accuracy: 0.7359
Epoch 16/100
35/35 [==============================] - 0s 1ms/step - loss: 3.9112 - accuracy: 0.7514
Epoch 17/100
35/35 [==============================] - 0s 1ms/step - loss: 3.7055 - accuracy: 0.7577
Epoch 18/100
35/35 [==============================] - 0s 1ms/step - loss: 3.1189 - accuracy: 0.7450
Epoch 19/100
35/35 [==============================] - 0s 1ms/step - loss: 3.8160 - accuracy: 0.7514
Epoch 20/100
35/35 [==============================] - 0s 1ms/step - loss: 2.8254 - accuracy: 0.7514
Epoch 21/100
35/35 [==============================] - 0s 1ms/step - loss: 2.9795 - accuracy: 0.7514
Epoch 22/100
35/35 [==============================] - 0s 1ms/step - loss: 2.5842 - accuracy: 0.7441
Epoch 23/100
35/35 [==============================] - 0s 1ms/step - loss: 3.5313 - accuracy: 0.7396
Epoch 24/100
35/35 [==============================] - 0s 1ms/step - loss: 2.6328 - accuracy: 0.7405
Epoch 25/100
35/35 [==============================] - 0s 1ms/step - loss: 3.0812 - accuracy: 0.7332
Epoch 26/100
35/35 [==============================] - 0s 1ms/step - loss: 3.3448 - accuracy: 0.7223
Epoch 27/100
35/35 [==============================] - 0s 1ms/step - loss: 3.3458 - accuracy: 0.7396
Epoch 28/100
35/35 [==============================] - 0s 1ms/step - loss: 2.3265 - accuracy: 0.7568
Epoch 29/100
35/35 [==============================] - 0s 1ms/step - loss: 3.6201 - accuracy: 0.7332
Epoch 30/100
35/35 [==============================] - 0s 1ms/step - loss: 3.2129 - accuracy: 0.7405
Epoch 31/100
35/35 [==============================] - 0s 1ms/step - loss: 2.0672 - accuracy: 0.7441
Epoch 32/100
35/35 [==============================] - 0s 1ms/step - loss: 3.8753 - accuracy: 0.7278
Epoch 33/100
35/35 [==============================] - 0s 1ms/step - loss: 2.1613 - accuracy: 0.7595
Epoch 34/100
35/35 [==============================] - 0s 1ms/step - loss: 2.8500 - accuracy: 0.7486
Epoch 35/100
35/35 [==============================] - 0s 1ms/step - loss: 2.8999 - accuracy: 0.7296
Epoch 36/100
35/35 [==============================] - 0s 1ms/step - loss: 2.6142 - accuracy: 0.7305
Epoch 37/100
35/35 [==============================] - 0s 1ms/step - loss: 1.9446 - accuracy: 0.7350
Epoch 38/100
35/35 [==============================] - 0s 1ms/step - loss: 1.6198 - accuracy: 0.7577
Epoch 39/100
35/35 [==============================] - 0s 1ms/step - loss: 2.0649 - accuracy: 0.7559
Epoch 40/100
35/35 [==============================] - 0s 1ms/step - loss: 2.3143 - accuracy: 0.7423
Epoch 41/100
35/35 [==============================] - 0s 1ms/step - loss: 1.8874 - accuracy: 0.7350
Epoch 42/100
35/35 [==============================] - 0s 1ms/step - loss: 1.7584 - accuracy: 0.7387
Epoch 43/100
35/35 [==============================] - 0s 1ms/step - loss: 2.2575 - accuracy: 0.7468
Epoch 44/100
35/35 [==============================] - 0s 1ms/step - loss: 2.0131 - accuracy: 0.7505
Epoch 45/100
35/35 [==============================] - 0s 1ms/step - loss: 2.3097 - accuracy: 0.7377
Epoch 46/100
35/35 [==============================] - 0s 1ms/step - loss: 2.2734 - accuracy: 0.7514
Epoch 47/100
35/35 [==============================] - 0s 1ms/step - loss: 1.9721 - accuracy: 0.7532
Epoch 48/100
35/35 [==============================] - 0s 1ms/step - loss: 1.5284 - accuracy: 0.7495
Epoch 49/100
35/35 [==============================] - 0s 1ms/step - loss: 1.9178 - accuracy: 0.7641
Epoch 50/100
35/35 [==============================] - 0s 1ms/step - loss: 1.4334 - accuracy: 0.7641
Epoch 51/100
35/35 [==============================] - 0s 1ms/step - loss: 1.7835 - accuracy: 0.7477
Epoch 52/100
35/35 [==============================] - 0s 1ms/step - loss: 1.5053 - accuracy: 0.7668
Epoch 53/100
35/35 [==============================] - 0s 1ms/step - loss: 1.4860 - accuracy: 0.7722
Epoch 54/100
35/35 [==============================] - 0s 1ms/step - loss: 1.4590 - accuracy: 0.7677
Epoch 55/100
35/35 [==============================] - 0s 1ms/step - loss: 1.8190 - accuracy: 0.7423
Epoch 56/100
35/35 [==============================] - 0s 1ms/step - loss: 1.3629 - accuracy: 0.7731
Epoch 57/100
35/35 [==============================] - 0s 1ms/step - loss: 1.2866 - accuracy: 0.7704
Epoch 58/100
35/35 [==============================] - 0s 1ms/step - loss: 1.6213 - accuracy: 0.7559
Epoch 59/100
35/35 [==============================] - 0s 1ms/step - loss: 1.4210 - accuracy: 0.7641
Epoch 60/100
35/35 [==============================] - 0s 1ms/step - loss: 1.4566 - accuracy: 0.7632
Epoch 61/100
35/35 [==============================] - 0s 1ms/step - loss: 1.0428 - accuracy: 0.7822
Epoch 62/100
35/35 [==============================] - 0s 1ms/step - loss: 1.2745 - accuracy: 0.7595
Epoch 63/100
35/35 [==============================] - 0s 1ms/step - loss: 2.6580 - accuracy: 0.7604
Epoch 64/100
35/35 [==============================] - 0s 1ms/step - loss: 1.8207 - accuracy: 0.7604
Epoch 65/100
35/35 [==============================] - 0s 1ms/step - loss: 1.5728 - accuracy: 0.7650
Epoch 66/100
35/35 [==============================] - 0s 1ms/step - loss: 1.1386 - accuracy: 0.7713
Epoch 67/100
35/35 [==============================] - 0s 1ms/step - loss: 1.6285 - accuracy: 0.7532
Epoch 68/100
35/35 [==============================] - 0s 1ms/step - loss: 0.9975 - accuracy: 0.7895
Epoch 69/100
35/35 [==============================] - 0s 1ms/step - loss: 1.2760 - accuracy: 0.7650
Epoch 70/100
35/35 [==============================] - 0s 1ms/step - loss: 1.2429 - accuracy: 0.7650
Epoch 71/100
35/35 [==============================] - 0s 1ms/step - loss: 1.5631 - accuracy: 0.7849
Epoch 72/100
35/35 [==============================] - 0s 1ms/step - loss: 1.4386 - accuracy: 0.7532
Epoch 73/100
35/35 [==============================] - 0s 1ms/step - loss: 0.8934 - accuracy: 0.7849
Epoch 74/100
35/35 [==============================] - 0s 1ms/step - loss: 1.2586 - accuracy: 0.7840
Epoch 75/100
35/35 [==============================] - 0s 1ms/step - loss: 1.0972 - accuracy: 0.7976
Epoch 76/100
35/35 [==============================] - 0s 1ms/step - loss: 3.3269 - accuracy: 0.7459
Epoch 77/100
35/35 [==============================] - 0s 1ms/step - loss: 1.6780 - accuracy: 0.7686
Epoch 78/100
35/35 [==============================] - 0s 1ms/step - loss: 0.9586 - accuracy: 0.7940
Epoch 79/100
35/35 [==============================] - 0s 1ms/step - loss: 2.0132 - accuracy: 0.7441
Epoch 80/100
35/35 [==============================] - 0s 1ms/step - loss: 1.1768 - accuracy: 0.7886
Epoch 81/100
35/35 [==============================] - 0s 1ms/step - loss: 1.2311 - accuracy: 0.7777
Epoch 82/100

35/35 [==============================] - 0s 1ms/step - loss: 1.0408 - accuracy: 0.7849
Epoch 83/100
35/35 [==============================] - 0s 1ms/step - loss: 2.4151 - accuracy: 0.7477
Epoch 84/100
35/35 [==============================] - 0s 1ms/step - loss: 0.8068 - accuracy: 0.8058
Epoch 85/100
35/35 [==============================] - 0s 1ms/step - loss: 1.1013 - accuracy: 0.7904
Epoch 86/100
35/35 [==============================] - 0s 1ms/step - loss: 0.9980 - accuracy: 0.7868
Epoch 87/100
35/35 [==============================] - 0s 1ms/step - loss: 0.7838 - accuracy: 0.8203
Epoch 88/100
35/35 [==============================] - 0s 1ms/step - loss: 1.0828 - accuracy: 0.7895
Epoch 89/100
35/35 [==============================] - 0s 1ms/step - loss: 0.9568 - accuracy: 0.7995
Epoch 90/100
35/35 [==============================] - 0s 1ms/step - loss: 1.5434 - accuracy: 0.7731
Epoch 91/100
35/35 [==============================] - 0s 1ms/step - loss: 1.8482 - accuracy: 0.7441
Epoch 92/100
35/35 [==============================] - 0s 1ms/step - loss: 0.8520 - accuracy: 0.7958
Epoch 93/100
35/35 [==============================] - 0s 1ms/step - loss: 1.2854 - accuracy: 0.7777
Epoch 94/100
35/35 [==============================] - 0s 1ms/step - loss: 1.0445 - accuracy: 0.7940
Epoch 95/100
35/35 [==============================] - 0s 1ms/step - loss: 1.4504 - accuracy: 0.7777
Epoch 96/100
35/35 [==============================] - 0s 1ms/step - loss: 0.9313 - accuracy: 0.7913
Epoch 97/100
35/35 [==============================] - 0s 1ms/step - loss: 0.8992 - accuracy: 0.8031
Epoch 98/100
35/35 [==============================] - 0s 1ms/step - loss: 2.2118 - accuracy: 0.7514
Epoch 99/100
35/35 [==============================] - 0s 1ms/step - loss: 1.5367 - accuracy: 0.7940
Epoch 100/100
35/35 [==============================] - 0s 1ms/step - loss: 0.7274 - accuracy: 0.8031

In [14]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.9587 - accuracy: 0.8533 - 141ms/epoch - 12ms/step
Loss: 0.9586783051490784, Accuracy: 0.85326087474823